### ISSUE TITLE
[Feature Request] Multiple stability numbers from varying wind conditions on one plot  

### ISSUE THREAD

**Issue by Crayok** [openrocket/openrocket#2539] opened 2024-08-14 16:27 UTC
I was hoping, with the stability plots that there might be a way to do multiple plots with various wind speeds and show the resulting stability numbers on one chart.

For most rockets, this is not really an issue and the displayed stability number on the main page is fine but as flyers produce high performance designs or hit the edges of stability, that number is questionable.  This plot can be done now but requires going in and editing the wind numbers, redoing the plots, then doing some work to get it on one chart in excel.

For the university teams I have always ask for the stability plots with varying winds and to ignore the front page stability number.  When they see these plots they get a better sense what CP/CG relationships mean....

**Comment by SiboVG** [comment] 2024-08-14 16:57
Duplicate of #1485.

**Closed by SiboVG** 2024-08-14 16:57 UTC
Labels: Feature request
