### ISSUE TITLE
"Parts Detail" doesn't include parts on pods

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2281] opened 2023-08-01 19:56 UTC
When doing "Print design info", the Parts Detail page does not include the components that are children of pods.  This is easily demonstrated with one of the pods demo designs.

**Comment by SiboVG** [comment] 2023-08-01 21:31
Duplicate of #2084, already fixed.

**Closed by SiboVG** 2023-08-01 21:31 UTC
Labels: bug
