### ISSUE TITLE
lots of copies dragging

### ISSUE THREAD

**Issue by rocketcol** [openrocket/openrocket#2408] opened 2023-11-20 09:39 UTC
using latest version of open rocket
when using it i get lots of copies when i drag the mouse.
i cannot see what to do then.

**Comment by SiboVG** [comment] 2023-11-20 09:42
> using latest version of open rocket when using it i get lots of copies when i drag the mouse. i cannot see what to do then.

Please give us more details:
- provide screenshots
- what's your operating system

**Comment by rocketcol** [comment] 2023-11-20 10:26
Operating System
Windows 10 Pro 64-bit

CPU
Intel Core i9
Cores 8
Threads 16
Name Intel Core i9
Code Name Kaby Lake
Package Socket 1151 LGA
Technology 14nm
Specification Intel Core i9-9900K CPU @ 3.60GHz

RAM
Memory
Size 32688 MBytes

Graphics
Monitor
Name PL2730Q on NVIDIA GeForce RTX 2070
Current Resolution 2048x1152 pixels
Work Resolution 2048x1112 pixels
State Enabled, Primary
Monitor Width 2560
Monitor Height 1440
Monitor BPP 32 bits per pixel
Monitor Frequency 59 Hz
Device \\.\DISPLAY1\Monitor0
NVIDIA GeForce RTX 2070
Manufacturer NVIDIA
Model GeForce RTX 2070
Device ID 10DE-1F07
Revision A2
Subvendor ASUStek Computer Inc (1043)
Current Performance Level Level 0
Bus Interface PCI Express x8
Temperature 43 °C
Driver version 31.0.15.3623
BIOS Version 90.06.2e.80.a5
Memory 4095 MB

**Comment by SiboVG** [comment] 2023-11-20 13:30
Thank you for the info! Could you also please upload screenshots of the effect you're seeing?

**Comment by rocketcol** [comment] 2023-11-20 15:03
i did attach one to that email

**Comment by SiboVG** [comment] 2023-11-20 15:20
Yeah, attaching attachment to GitHub mails doesn’t work. You need to go to GitHub and post a new comment with the image: https://github.com/openrocket/openrocket/issues/2408

From: rocketcol ***@***.***>
Date: Monday, 20 November 2023 at 16:03
To: openrocket/openrocket ***@***.***>
Cc: Sibo Van Gool ***@***.***>, Comment ***@***.***>
Subject: Re: [openrocket/openrocket] lots of copies dragging (Issue #2408)
i did attach one to that email

**Comment by rocketcol** [comment] 2023-11-20 15:28
![Capture](https://github.com/openrocket/openrocket/assets/24721226/c4b96aca-7ea5-4813-b891-92f845d4bfd5)

**Comment by JoePfeiffer** [comment] 2023-11-20 15:41
Also, when you say "latest version", do you mean 23.09? There have been some bugfixes incorporated in this version that address similar issues.

**Comment by rocketcol** [comment] 2023-11-20 19:06
Yes, exactly.

**Comment by rocketcol** [comment] 2023-11-20 19:06
yes downloaded latest version

**Comment by rocketcol** [comment] 2023-11-20 19:17
as i move the mouse it just keeps putting widows on top of each other

**Comment by SiboVG** [comment] 2023-11-21 15:35
@rocketcol could you check whether the Display Scaling setting of your display is set to 100%?
https://support.microsoft.com/en-us/windows/view-display-settings-in-windows-37f0e05e-98a9-474c-317a-e85422daa8bb
![image](https://github.com/openrocket/openrocket/assets/11031519/a31eab50-be9a-4b1a-b484-2c2e94841a91)

**Comment by rocketcol** [comment] 2023-11-22 10:45
no it was set to 125% so changed it to 100% and seemed to be ok for a while
then started again

**Comment by SiboVG** [comment] 2024-08-22 07:39
Duplicate of #1667.

**Closed by SiboVG** 2024-08-22 07:39 UTC
