### ISSUE TITLE
Nose Cone models matching current nose cones being sold

### ISSUE THREAD

**Issue by HandemanTRA** [openrocket/openrocket#2088] opened 2023-02-27 22:50 UTC
I've only bought fiberglass kits for the last few years.  All of the nose cones come with a round tubular area at the bottom that the coupler fits into.  This coupler is what forms the shoulder of the nose cone.

None of the nose cone type available in OR can be done like this.  They all start narrowing down from the base of the nose cone.  What I've been doing is using a nose cone that is shorter than what the kit comes with and adding a piece of BT to the end of the nose cone to accept the coupler tube that forms the shoulder.   All the nose cone models allow adding a shoulder, none come without a shoulder and/or allow a coupler tube to form the shoulder.  

It would be nice to pick a nose cone and be able to put a coupler tube inside the nose cone to form the shoulder without the coupler tube extending outside the nose cone.  That really mess up the Photo Shop views what looking at paint patterns.

Also, I haven't been able to find any nose cone types that actually matches the look of what manufacturers are shipping.  As long as they match the aerodynamics close, that really isn't a big deal.

Thanks...   

Jeff "Handeman" Boldig

**Comment by hcraigmiller** [comment] 2023-02-27 23:25
As to the request for a nose cone base feature, this is a duplicate of Issue #839. As to the addition of nose cones "that actually matches the look of what manufacturers are shipping," the parts library is imported from the [DB Cook enhanced parts library](https://github.com/dbcook/openrocket-database). Additional nose cones may be added there.

**Closed by hcraigmiller** 2023-02-27 23:25 UTC
Labels: Feature request
