### ISSUE TITLE
[Feature Request] Show calculated values on Override tab

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2095] opened 2023-03-03 01:53 UTC
Any time an override value can be entered, the calculated value should be shown for comparison.  This applies to mass, CG, and Cd overrides.

Presently, the calculated mass is shown at the bottom of the component editor; I think it should be shown in a location consistent with how the other two are implemented, even if it means a redundant display.

Calculated values should be shown for both the component and the full component tree underneath it, for a grand total of 6 values.  This means that whenever the user adds any override at all, it will be clear what change they are making.

I don't have a proposal for how the UI should look for this right now.

**Comment by SiboVG** [comment] 2023-03-04 16:02
Duplicate of #1629.

**Closed by SiboVG** 2023-03-04 16:02 UTC
Labels: Feature request
