### ISSUE TITLE
Packed parachute length changes between saves

### ISSUE THREAD

**Issue by sjh114961** [openrocket/openrocket#1803] opened 2022-11-09 22:05 UTC
Packed parachute length changes between saves without making any changes.
Original:
![Parachute1](https://user-images.githubusercontent.com/53155232/200951477-39cf9fc0-056a-4bac-9a09-7919b974814c.png)
After 1st save:
![Parachute2](https://user-images.githubusercontent.com/53155232/200951691-0343ab04-8261-443f-add9-35a2c092567c.png)
After 2nd save:
![Parachute3](https://user-images.githubusercontent.com/53155232/200951755-efea42cd-43d1-4906-80a6-e4b2ad064c06.png)

All that was done was a save NO Changes.

[snarkyD1.zip](https://github.com/openrocket/openrocket/files/9975484/snarkyD1.zip)

**Comment by SiboVG** [comment] 2022-11-09 22:50
This is a duplicate of #1723, which is fixed in #1726. The fix will be included in the next OR release.

**Closed by SiboVG** 2022-11-09 22:50 UTC
