### ISSUE TITLE
Can't Open OpenRocket

### ISSUE THREAD

**Issue by Dill18** [openrocket/openrocket#528] opened 2019-03-12 03:31 UTC
Hello. Brand new file downloads will not open. My java version is up to date too. How can I open the program?

**Comment by JoePfeiffer** [comment] 2019-03-13 23:14
Are you getting any sort of error message?  Also, what OS?

**Comment by Dill18** [comment] 2019-03-14 00:43
No, the download simply wouldn’t open after a complete download. I was later able to change the program that it opens with to the Java SE runtime thing, but this led to a black window popping up for what seemed about half a second. I assume this was my PCs command window opening for a split second then closing. I was able to get the program to open after downloading the OpenRocket file from the dropbox link which I believe holds an .exe file. There just seems to be an issue with the .jar file. My system runs window 10.

**Comment by teyrana** [comment] 2019-03-14 02:30
This might be an duplicate of: 
https://github.com/openrocket/openrocket/issues/347

If you have java 9, 10, or 11, Openrocket won't run.

**Comment by nshire** [comment] 2019-03-21 03:34
Openrocket currently only works with Java 8 or below. 

If you are Ubuntu, make sure you have JDK 8 installed by running `sudo apt install openjdk-8-jre` .
Then, run OpenRocket by first specifying the java 8 install path `/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -jar [InstallDir]/OpenRocket.jar `

**Comment by neilweinstock** [comment] 2019-03-28 14:10
Sounds like he got it running using my packaged installer, which implies he's on Windows.

The packaged installer is the simplest solution in these cases.

**Comment by itshanney** [comment] 2020-04-06 22:18
Closing issue as reporter appears to be working and was encountering known issue of OR not running on Java 9+.

**Closed by itshanney** 2020-04-06 22:18 UTC
