### ISSUE TITLE
Can't type in Photo Studio spinners

### ISSUE THREAD

**Issue by SiboVG** [openrocket/openrocket#947] opened 2021-06-15 18:30 UTC
I can't seem to type any numbers in the spinners of Photo Studio. When typing, nothing happens. I can change the value of the spinner using the up and down buttons, but typing doesn't work. Other spinners, like e.g. 'Shape parameter' of the Nose cone works as it should.

![Screenshot 2021-06-15 at 20 26 30](https://user-images.githubusercontent.com/11031519/122104797-59704900-ce18-11eb-8cec-85c4eb33253f.png)
![Screenshot 2021-06-15 at 20 29 02](https://user-images.githubusercontent.com/11031519/122104806-5bd2a300-ce18-11eb-9f20-4a0285e996d4.png)

**Comment by hcraigmiller** [comment] 2021-06-15 20:23
May be duplicate of Issue #873.

**Comment by SiboVG** [comment] 2021-06-15 20:25
Ah yes, sorry, didn't notice, this issue is irrelevant then

**Closed** 2021-06-15 20:25 UTC
