### ISSUE TITLE
Recovery device name isn't updated in Recovery tab

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#524] opened 2019-03-09 22:07 UTC
Working on a dual deploy design, I originally didn't override the default parachute names ("Parachute").  I went back and renamed them "Main" and "Drogue".  When I went to the Motors & Configuration -> Recovery tab, I saw the parachutes were still just named "Parachute".  When I saved the design and restarted OR, the names had been updated (is this just an example of Issue 329?).

**Comment by teyrana** [comment] 2019-03-09 22:40
>  (is this just an example of Issue 329?)

Probably.  no great in harm in having an specific, explicitly reported issue for it, though.

**Comment by teyrana** [comment] 2020-05-17 20:40
@JoePfeiffer 

Working through our backlog; I have tested this, and it seems to be updating as expected now. 

Unless you can you reproduce it, I'd like to close this issue.

**Comment by JoePfeiffer** [comment] 2020-05-17 22:33
Looks like it's still there -- just opened a design, changed the name of the drogue chute to "Test"
![tree](https://user-images.githubusercontent.com/3065196/82161642-b7b8aa00-985b-11ea-9a5e-c88182ecd685.png)
but when I look at the recovery tab it's still named "Drogue"
![tab](https://user-images.githubusercontent.com/3065196/82161653-cbfca700-985b-11ea-9e73-455f7ad40e66.png)

When I save the design, exit OR, get back in and reopen the design, the name has changed

**Comment by teyrana** [comment] 2020-05-17 22:51
Okay, thank you for claryfying.  I can reproduce it now.

So, it's not *always* happening-- it updates in the component-tree, but not in the configuration > recovery tab.  hmm.

**Comment by JoePfeiffer** [comment] 2020-05-17 22:58
That seems to be consistent -- it seems to always update in the component tree, and never in the configuration>recovery tab.

**Closed** 2020-05-31 04:28 UTC
