### ISSUE TITLE
Support import of pods from Rocksim designs

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#1350] opened 2022-05-11 20:44 UTC
As far as I know, there is not presently any effort made to import pods from RKT files.  Even though OR pod functionality is presently limited compared to Rocksim, it might be worth some effort to understand what is possible, and see if we can at least partially import pods.

**Comment by JoePfeiffer** [comment] 2022-05-11 21:25
Duplicate of #1348 (and personally I regard it failing to import something that we actually support to be a bug)

**Closed by JoePfeiffer** 2022-05-11 21:25 UTC
Labels: Feature request

**Comment by neilweinstock** [comment] 2022-05-12 00:53
I call it a feature because as far as I know we *can't* implement general-purpose pod import.  It'll need to be carefully limited and focused.

Either way. :)
