### ISSUE TITLE
Edit Box issue

### ISSUE THREAD

**Issue by crscholz** [openrocket/openrocket#1625] opened 2022-08-29 01:26 UTC
I run into issues with OR when editing a part and the edit dialogue box won't open. This issue occurs when running OR on my laptop and then connecting to an external monitor.

**Comment by SiboVG** [comment] 2022-08-29 06:58
This appears to be a duplicate of #1470, which has been fixed and will be included in the next beta release. You can also check the [this](https://www.reddit.com/r/rocketry/comments/s39c1k/openrocket_edit_window_does_not_open/?utm_source=share&utm_medium=web2x&context=3) or [this](https://www.reddit.com/r/rocketry/comments/m1e6tn/cant_edit_parts_in_openrocket/) Reddit post that contain a way of fixing your issue.

**Closed by SiboVG** 2022-08-29 06:58 UTC
