### ISSUE TITLE
Feature request:export the design to stl file for 3d printing.

### ISSUE THREAD

**Issue by ZCY571864845** [openrocket/openrocket#1609] opened 2022-08-23 15:16 UTC
Proposal: add a function to export the design to stl or stp file for 3d printing.

**Comment by SiboVG** [comment] 2022-08-23 15:20
Duplicate of #604. This is a feature that's also high on my wish-list, but we need to do a full rewrite of our 3D engine, which will take its time. So don't expect this feature to be included in OR soon.

**Closed by SiboVG** 2022-08-23 15:20 UTC

**Comment by ZCY571864845** [comment] 2022-08-23 15:26
I see,expecting...
