### ISSUE TITLE
Cannot launch openrocket on Linux Arch64

### ISSUE THREAD

**Issue by snrkl** [openrocket/openrocket#484] opened 2018-11-24 06:49 UTC
```
snrkl@rincewind:~$ uname -a
Linux rincewind 3.10.105-bsp-1.2 #2 SMP PREEMPT Sat Oct 27 19:24:05 IST 2018 aarch64 aarch64 aarch64 GNU/Linux

snrkl@rincewind:~$ which java
/usr/bin/java
snrkl@rincewind:~$ java --version
openjdk 10.0.2 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3)
OpenJDK 64-Bit Server VM (build 10.0.2+13-Ubuntu-1ubuntu0.18.04.3, mixed mode)
snrkl@rincewind:~$ 

snrkl@rincewind:~$ cat /etc/lsb-release 
DISTRIB_ID=neon
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="KDE neon User Edition 5.14"

```

Console Output:
```
snrkl@rincewind:~$ java -jar ~/Downloads/OpenRocket-15.03.jar 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$2 (file:/home/snrkl/Downloads/OpenRocket-15.03.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$2
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

---------- Bug report ----------

Please include a description about what actions you were performing when the exception occurred:
Launched OpenRocket using java -j OpenRocket-15.03.jar

Include your email address (optional; it helps if we can contact you in case we need additional information):

(Do not modify anything below this line.)
---------- Exception stack trace ----------
java.lang.RuntimeException: Error starting OpenRocket
	at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:40)
	at net.sf.openrocket.startup.OpenRocket.main(OpenRocket.java:32)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:38)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
	at net.sf.openrocket.startup.SwingStartup.main(SwingStartup.java:76)
	... 6 more
Caused by: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:125)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:521)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
	at com.google.inject.Guice.createInjector(Guice.java:95)
	at com.google.inject.Guice.createInjector(Guice.java:72)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at net.sf.openrocket.startup.SwingStartup.runInEDT(SwingStartup.java:143)
	at net.sf.openrocket.startup.SwingStartup.access$000(SwingStartup.java:43)
	at net.sf.openrocket.startup.SwingStartup$1.run(SwingStartup.java:79)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:73)
	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 35 more
Caused by: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3119)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2268)
	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:662)
	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:151)
	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:585)
	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:543)
	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:529)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
	at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:41)
	at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:125)
	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:95)
	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
	... 45 more
Caused by: java.lang.ClassNotFoundException: javax.script.ScriptEngineFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 67 more

---------- Thread information ----------
Thread[main,5,main]

---------- System information ----------
OpenRocket version: 15.03
OpenRocket source: default
OpenRocket location: /home/snrkl/Downloads/OpenRocket-15.03.jar
JOGL version: 2.1.5
Current default locale: en_AU
System properties:
  awt.toolkit=sun.awt.X11.XToolkit
  file.encoding=UTF-8
  file.encoding.pkg=sun.io
  file.separator=/
  java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
  java.awt.printerjob=sun.print.PSPrinterJob
  java.class.path=/home/snrkl/Downloads/OpenRocket-15.03.jar
  java.class.version=54.0
  java.home=/usr/lib/jvm/java-11-openjdk-arm64
  java.io.tmpdir=/tmp
  java.library.path=/usr/java/packages/lib:/usr/lib/aarch64-linux-gnu/jni:/lib/aarch64-linux-gnu:/usr/lib/aarch64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
  java.runtime.name=OpenJDK Runtime Environment
  java.runtime.version=10.0.2+13-Ubuntu-1ubuntu0.18.04.3
  java.specification.name=Java Platform API Specification
  java.specification.vendor=Oracle Corporation
  java.specification.version=10
  java.vendor=Oracle Corporation
  java.vendor.url=http://java.oracle.com/
  java.vendor.url.bug=http://bugreport.java.com/bugreport/
  java.version=10.0.2
  java.version.date=2018-07-17
  java.vm.compressedOopsMode=32-bit
  java.vm.info=mixed mode
  java.vm.name=OpenJDK 64-Bit Server VM
  java.vm.specification.name=Java Virtual Machine Specification
  java.vm.specification.vendor=Oracle Corporation
  java.vm.specification.version=10
  java.vm.vendor=Oracle Corporation
  java.vm.version=10.0.2+13-Ubuntu-1ubuntu0.18.04.3
  jdk.debug=release
  line.separator=\u000a
  os.arch=aarch64
  os.name=Linux
  os.version=3.10.105-bsp-1.2
  path.separator=:
  sun.arch.data.model=64
  sun.awt.enableExtraMouseButtons=true
  sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
  sun.boot.library.path=/usr/lib/jvm/java-11-openjdk-arm64/lib
  sun.cpu.endian=little
  sun.cpu.isalist=
  sun.font.fontmanager=sun.awt.X11FontManager
  sun.io.unicode.encoding=UnicodeLittle
  sun.java.command=/home/snrkl/Downloads/OpenRocket-15.03.jar
  sun.java.launcher=SUN_STANDARD
  sun.jnu.encoding=UTF-8
  sun.management.compiler=HotSpot 64-Bit Tiered Compilers
  sun.os.patch.level=unknown
  user.country=AU
  user.dir=/home/snrkl
  user.home=/home/snrkl
  user.language=en
  user.name=snrkl
  user.timezone=Australia/Brisbane
---------- Error log ----------
   1      0.003 INFO   (SwingStartup.java:61) Starting up OpenRocket version 15.03
   2      0.004 INFO   (SwingStartup.java:64) Checking for graphics head
   3      0.031 INFO   (SwingStartup.java:75) Moving startup to EDT
   4      1.494 INFO   (SwingStartup.java:129) Initializing the splash screen
   5      3.893 INFO   (SwingStartup.java:133) Registering exception handler
   6      3.999 INFO   (SwingStartup.java:139) Loading databases
   7      8.367 ERROR  (SwingExceptionHandler.java:48) Handling uncaught exception on thread=Thread[main,5,main]
   > java.lang.RuntimeException: Error starting OpenRocket
   > 	at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:40)
   > 	at net.sf.openrocket.startup.OpenRocket.main(OpenRocket.java:32)
   > Caused by: java.lang.reflect.InvocationTargetException
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   > 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
   > 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
   > 	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
   > 	at net.sf.openrocket.startup.jij.JarInJarStarter.runMain(JarInJarStarter.java:38)
   > 	... 1 more
   > Caused by: java.lang.reflect.InvocationTargetException
   > 	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1367)
   > 	at java.desktop/java.awt.EventQueue.invokeAndWait(EventQueue.java:1342)
   > 	at java.desktop/javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1480)
   > 	at net.sf.openrocket.startup.SwingStartup.main(SwingStartup.java:76)
   > 	... 6 more
   > Caused by: com.google.inject.internal.util.$ComputationException: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
   > 	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
   > 	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
   > 	at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:49)
   > 	at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:125)
   > 	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:521)
   > 	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
   > 	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
   > 	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
   > 	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
   > 	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
   > 	at com.google.inject.internal.FactoryProxy.notify(FactoryProxy.java:46)
   > 	at com.google.inject.internal.ProcessedBindingData.runCreationListeners(ProcessedBindingData.java:50)
   > 	at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:133)
   > 	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:106)
   > 	at com.google.inject.Guice.createInjector(Guice.java:95)
   > 	at com.google.inject.Guice.createInjector(Guice.java:72)
   > 	at com.google.inject.Guice.createInjector(Guice.java:62)
   > 	at net.sf.openrocket.startup.SwingStartup.runInEDT(SwingStartup.java:143)
   > 	at net.sf.openrocket.startup.SwingStartup.access$000(SwingStartup.java:43)
   > 	at net.sf.openrocket.startup.SwingStartup$1.run(SwingStartup.java:79)
   > 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:303)
   > 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
   > 	at java.desktop/java.awt.EventQueue.access$600(EventQueue.java:97)
   > 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
   > 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
   > 	at java.base/java.security.AccessController.doPrivileged(Native Method)
   > 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
   > 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
   > 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
   > 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
   > Caused by: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
   > 	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
   > 	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
   > 	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
   > 	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:73)
   > 	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
   > 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
   > 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
   > 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
   > 	... 35 more
   > Caused by: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
   > 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
   > 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3119)
   > 	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2268)
   > 	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:662)
   > 	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
   > 	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:151)
   > 	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:585)
   > 	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:543)
   > 	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:529)
   > 	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
   > 	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
   > 	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
   > 	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
   > 	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
   > 	at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:41)
   > 	at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:125)
   > 	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:95)
   > 	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
   > 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
   > 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
   > 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
   > 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
   > 	... 45 more
   > Caused by: java.lang.ClassNotFoundException: javax.script.ScriptEngineFactory
   > 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
   > 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
   > 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
   > 	... 67 more
  53      0.000 STDERR (-) ===== 45 STDERR lines removed =====
  53      8.401 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
  54      8.402 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
  55      8.402 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
  56      8.403 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
  57      8.404 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
  58      8.405 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
  59      8.405 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
  60      8.406 STDERR (SwingExceptionHandler.java:49) 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
  61      8.407 STDERR (SwingExceptionHandler.java:49) Caused by: com.google.inject.internal.util.$ComputationException: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
  62      8.408 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:553)
  63      8.409 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:419)
  64      8.410 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$CustomConcurrentHashMap$ComputingImpl.get(CustomConcurrentHashMap.java:2041)
  65      8.410 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.FailableCache.get(FailableCache.java:50)
  66      8.411 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore.get(MembersInjectorStore.java:65)
  67      8.412 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:73)
  68      8.413 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:28)
  69      8.413 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:36)
  70      8.414 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:32)
  71      8.414 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
  72      8.415 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
  73      8.415 STDERR (SwingExceptionHandler.java:49) 	... 35 more
  74      8.416 STDERR (SwingExceptionHandler.java:49) Caused by: java.lang.NoClassDefFoundError: javax/script/ScriptEngineFactory
  75      8.417 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
  76      8.418 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3119)
  77      8.418 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2268)
  78      8.419 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.spi.InjectionPoint.getInjectionPoints(InjectionPoint.java:662)
  79      8.420 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.spi.InjectionPoint.forInstanceMethodsAndFields(InjectionPoint.java:356)
  80      8.420 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.ConstructorBindingImpl.getInternalDependencies(ConstructorBindingImpl.java:151)
  81      8.421 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.getInternalDependencies(InjectorImpl.java:585)
  82      8.421 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.cleanup(InjectorImpl.java:543)
  83      8.422 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.initializeJitBinding(InjectorImpl.java:529)
  84      8.422 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:847)
  85      8.423 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:772)
  86      8.425 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:256)
  87      8.426 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:205)
  88      8.426 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.InjectorImpl.getInternalFactory(InjectorImpl.java:853)
  89      8.427 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.SingleFieldInjector.<init>(SingleFieldInjector.java:41)
  90      8.428 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore.getInjectors(MembersInjectorStore.java:125)
  91      8.429 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore.createWithListeners(MembersInjectorStore.java:95)
  92      8.429 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore.access$000(MembersInjectorStore.java:34)
  93      8.430 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:42)
  94      8.431 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.MembersInjectorStore$1.create(MembersInjectorStore.java:39)
  95      8.432 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.FailableCache$1.apply(FailableCache.java:39)
  96      8.433 STDERR (SwingExceptionHandler.java:49) 	at com.google.inject.internal.util.$MapMaker$StrategyImpl.compute(MapMaker.java:549)
  97      8.434 STDERR (SwingExceptionHandler.java:49) 	... 45 more
  98      8.435 STDERR (SwingExceptionHandler.java:49) Caused by: java.lang.ClassNotFoundException: javax.script.ScriptEngineFactory
  99      8.436 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
 100      8.437 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
 101      8.438 STDERR (SwingExceptionHandler.java:49) 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
 102      8.438 STDERR (SwingExceptionHandler.java:49) 	... 67 more
 103      8.439 INFO   (SwingExceptionHandler.java:64) Exception handler not on EDT, invoking dialog on EDT
 104      8.445 INFO   (SwingExceptionHandler.java:201) Showing Exception dialog
 105     13.168 USER   (SwingExceptionHandler.java:220) User requested sending bug report
 106     13.207 DEBUG  (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

**Comment by JoePfeiffer** [comment] 2018-12-04 18:47
The current version of openrocket requires java8, and you appear to have java10 as your default.  If you also have java8 on your system, you should be able to run /path/to/java8/java -jar OpenRocket-15.03.jar

For example, on my Debian system, I can run
snowball:613$ /usr/lib/jvm/java-8-oracle/bin/java -jar /usr/lib/openrocket/OpenRocket-15.03.jar

**Comment by kernelsmith** [comment] 2019-03-14 22:02
yeah, this is kind of a dupe of #347. For some reason the max compatible version of 8 is not mentioned anywhere obvious so we all keep opening issues like this

**Comment by gallopinggoose6** [comment] 2019-04-15 04:27
Then we should close this issue and we make 347 a bigger priority @JoePfeiffer @snrkl. Also, in addition we should mention that Java 8 is the max somewhere, as kernelsmith was saying.

**Comment by wolsen** [comment] 2020-03-21 18:51
This is now fixed in unstable

**Comment by teyrana** [comment] 2020-03-22 00:45
@wolsen @snrkl 
Closed as resolved.

**Closed by teyrana** 2020-03-22 00:45 UTC
