### ISSUE TITLE
[Feature Request] <svg export>

### ISSUE THREAD

**Issue by jet689** [openrocket/openrocket#2460] opened 2024-02-18 06:05 UTC
I prefer to model in fusion 360 and would love a easier way to use openrocket with it.

There is many ways this could be done but maybe svg export for a couple views of your design. so you can easily get your nose cone and fin shape into f360 sketches.

**Comment by KE6MTO** [comment] 2024-02-19 00:00
I would second this. Would love to have an option to export the "Face" of centering rings and fins to SVG. That way it can be directly imported into laser cutting software like LightBurn.

**Comment by SiboVG** [comment] 2024-02-19 11:11
Exporting fins to SVG has been implemented in #2452 (for the next release). Since this is a duplicate of #242, I will close this issue.

**Closed by SiboVG** 2024-02-19 11:11 UTC
Labels: Feature request
