### ISSUE TITLE
GUI Screen Layering AMD Processor

### ISSUE THREAD

**Issue by Canoes4296** [openrocket/openrocket#1982] opened 2023-01-17 17:28 UTC
---------- Bug report ----------

Include detailed steps on how to trigger the bug:
(You can edit text directly in this window)

1.Go to preferences
2.Units
3.Edit a unit, screen layering occurs

What does the software do and what in your opinion should it do in the case described above:
Screen Layering, however I cannot switch to Intel Integrated as I have an AMD CPU

Include your email address (optional; it helps if we can contact you in case we need additional information):
rcl.talks@gmail.com

(Do not modify anything below this line.)
---------- System information ----------
OpenRocket version: 22.02.beta.05
OpenRocket source: default
OpenRocket location: C:\Program Files\OpenRocket\.\OpenRocket.jar
JOGL version: 2.4.0-rc-20210111
Current default locale: en_US
System properties:
awt.toolkit=sun.awt.windows.WToolkit
exe4j.consoleCodepage=cp0
exe4j.isInstall4j=true
exe4j.launchName=C:\Program Files\OpenRocket\OpenRocket.exe
exe4j.moduleName=C:\Program Files\OpenRocket\OpenRocket.exe
exe4j.semaphoreName=Local\c:_program_files_openrocket_openrocket.exe0
exe4j.tempDir=
exe4j.unextractedPosition=0
file.encoding=Cp1252
file.separator=\
install4j.appDir=C:\Program Files\OpenRocket\
install4j.exeDir=C:\Program Files\OpenRocket\
install4j.launcherId=59
install4j.swt=false
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=C:\Program Files\OpenRocket\.install4j\i4jruntime.jar;C:\Program Files\OpenRocket\.\OpenRocket.jar
java.class.version=55.0
java.home=c:\program files\openrocket\jre
java.io.tmpdir=C:\Users\rclta\AppData\Local\Temp\
java.library.path=c:\program files\openrocket\jre\bin;C:\Program Files\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\MATLAB\R2021a\bin;C:\Program Files (x86)\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\PuTTY\;C:\Users\rclta\AppData\Local\Microsoft\WindowsApps;C:\Users\rclta\AppData\Local\GitHubDesktop\bin;C:\Program Files\Java\jdk1.8.0_301\bin;C:\Users\rclta\AppData\Local\Programs\Microsoft VS Code\bin
java.runtime.name=OpenJDK Runtime Environment
java.runtime.version=11.0.15+10-LTS
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=11
java.util.Arrays.useLegacyMergeSort=true
java.vendor=BellSoft
java.vendor.url=https://bell-sw.com/
java.vendor.url.bug=https://bell-sw.com/support
java.version=11.0.15
java.version.date=2022-04-19
java.vm.compressedOopsMode=Zero based
java.vm.info=mixed mode
java.vm.name=OpenJDK 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=11
java.vm.vendor=BellSoft
java.vm.version=11.0.15+10-LTS
jdk.debug=release
jnlp.jogamp.tmp.cache.root=jln4811447707141786860
line.separator=\u000d\u000a
os.arch=amd64
os.name=Windows 10
os.version=10.0
path.separator=;
sun.arch.data.model=64
sun.awt.enableExtraMouseButtons=true
sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
sun.boot.library.path=c:\program files\openrocket\jre\bin
sun.cpu.endian=little
sun.cpu.isalist=amd64
sun.desktop=windows
sun.io.unicode.encoding=UnicodeLittle
sun.java.command=C:\Program Files\OpenRocket\OpenRocket.exe
sun.jnu.encoding=Cp1252
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=
user.country=US
user.dir=C:\Program Files\OpenRocket
user.home=C:\Users\rclta
user.language=en
user.name=rclta
user.script=
user.timezone=America/New_York
user.variant=
---------- Error log ----------
1 0.001 INFO (SwingStartup.java:65) Starting up OpenRocket version 22.02.beta.05
2 0.002 INFO (SwingStartup.java:73) Checking for graphics head
3 0.003 INFO (SwingStartup.java:84) Moving startup to EDT
4 0.057 INFO (SwingStartup.java:176) Initializing the splash screen
5 0.107 INFO (SwingStartup.java:180) Registering exception handler
6 0.110 INFO (SwingStartup.java:186) Loading databases
7 1.362 INFO (TranslatorProvider.java:49) Using default locale en_US
8 1.374 INFO (TranslatorProvider.java:61) Set up translation for locale en_US, debug.currentFile=messages.properties
9 1.375 INFO (ComponentPresetDatabaseLoader.java:93) Loading component presets from datafiles/components
10 1.375 INFO (MotorDatabaseLoader.java:89) Starting reading serialized motor database
13 1.377 INFO (SwingStartup.java:198) Starting update check
14 1.381 INFO (SwingStartup.java:207) Setting best LAF
18 1.567 INFO (SwingStartup.java:224) Opening main application window
19 1.585 INFO (BasicFrame.java:1641) New action initiated
21 1.647 INFO (MotorDatabaseLoader.java:95) Ending reading serialized motor database, motorCount=1887
22 1.652 INFO (MotorDatabaseLoader.java:70) Starting reading user-defined motors
24 1.661 INFO (MotorDatabaseLoader.java:80) Ending reading user-defined motors, motorCount=1888
84 0.000 DEBUG (-) ===== 65 DEBUG lines removed =====
84 2.095 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/components/loc_precision.orc
85 2.103 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/components/loc_precision.orc contained 64 presets
86 2.105 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/components/madcow.orc
87 2.105 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/components/madcow.orc
88 2.124 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/components/madcow.orc contained 240 presets
89 2.126 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/components/mpc.orc
90 2.126 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/components/mpc.orc
91 2.142 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/components/mpc.orc contained 49 presets
92 2.142 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/components/publicmissiles-legacy.orc
93 2.142 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/components/publicmissiles-legacy.orc
94 2.163 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/components/publicmissiles-legacy.orc contained 115 presets
95 2.163 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/components/publicmissiles.orc
96 2.163 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/components/publicmissiles.orc
97 2.185 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/components/publicmissiles.orc contained 132 presets
98 2.186 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/components/quest.orc
99 2.186 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/components/quest.orc
100 2.198 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/components/quest.orc contained 71 presets
101 2.199 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/components/semroc-legacy.orc
102 2.199 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/components/semroc-legacy.orc
103 2.230 DEBUG (UpdateInfoRetriever.java:229) Update checker response code: 200
104 2.346 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/components/semroc-legacy.orc contained 874 presets
105 2.348 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/components/semroc.orc
106 2.348 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/components/semroc.orc
107 2.448 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/components/semroc.orc contained 1676 presets
108 2.451 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/components/top_flight.orc
109 2.451 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/components/top_flight.orc
110 2.454 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/components/top_flight.orc contained 34 presets
111 2.481 DEBUG (ComponentPresetDatabaseLoader.java:59) Time to load presets: 1106ms 4780 loaded from 29 files
112 2.489 DEBUG (BasicFrame.java:153) Instantiating new BasicFrame
113 2.490 DEBUG (BasicFrame.java:165) Constructing the BasicFrame UI
114 2.512 DEBUG (Icons.java:24) Starting to load icons
115 2.527 DEBUG (UpdateInfoRetriever.java:229) Update checker response code: 200
116 2.539 DEBUG (ReleaseInfo.java:43) Invalid release tag format for release: OpenRocket_technical_documentation-v13.05
117 2.539 DEBUG (ReleaseInfo.java:43) Invalid release tag format for release: Development_of_an_Open_Source_model_rocket_simulation-thesis-v20090520
118 2.540 INFO (UpdateInfoRetriever.java:153) Current build is latest version
119 2.556 DEBUG (Icons.java:106) Icons loaded
129 0.000 VBOSE (-) ===== 10 VBOSE lines removed =====
129 2.957 VBOSE (AbstractChangeSource.java:25) Adding change listeners, listener count is now 1
130 3.248 VBOSE (Rocket.java:480) Added ComponentChangeListener net.sf.openrocket.gui.dialogs.flightconfiguration.MotorMountTableModel@7c6ed2ab, current number of listeners is 7
131 3.256 VBOSE (Rocket.java:480) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.FlightConfigurableTableModel@7a6da73c, current number of listeners is 8
132 3.257 VBOSE (Rocket.java:480) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.RecoveryConfigurationPanel$$Lambda$230/0x0000000800522840@8785712, current number of listeners is 9
133 3.261 VBOSE (Rocket.java:480) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.SeparationConfigurationPanel$2@7ee58b83, current number of listeners is 10
134 3.276 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
135 3.296 DEBUG (RocketFigure3d.java:141) Initializing RocketFigure3D OpenGL Canvas
136 3.296 DEBUG (RocketFigure3d.java:143) Setting up GL capabilities...
137 3.296 VBOSE (RocketFigure3d.java:145) GL - Getting Default Profile
138 4.148 VBOSE (RocketFigure3d.java:148) GL - creating GLCapabilities
139 4.148 VBOSE (RocketFigure3d.java:158) GL - Not enabling AA by user pref
140 4.148 VBOSE (RocketFigure3d.java:162) GL - Creating GLJPanel
141 4.153 VBOSE (RocketFigure3d.java:169) GL - Registering as GLEventListener on canvas
142 4.153 VBOSE (RocketFigure3d.java:172) GL - Adding canvas to this JPanel
143 4.153 VBOSE (RocketFigure3d.java:175) GL - Setting up mouse listeners
144 4.154 VBOSE (RocketFigure3d.java:178) GL - Rasterizing Carets
145 4.166 VBOSE (DoubleModel.java:920) DoubleModel[constant=0.0] adding listener (total 1): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$1@3a39c9cf
146 4.184 VBOSE (DoubleModel.java:920) DoubleModel[constant=0.0] adding listener (total 2): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
147 4.184 VBOSE (DoubleModel.java:920) DoubleModel[constant=0.0] adding listener (total 3): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
148 4.184 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
149 4.185 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
150 4.185 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
151 4.185 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
152 4.186 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
153 4.187 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
154 4.187 VBOSE (Rocket.java:480) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@4e874c5a, current number of listeners is 11
155 4.203 VBOSE (Rocket.java:480) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@29eabded, current number of listeners is 12
156 4.205 VBOSE (Rocket.java:480) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@12143bbe, current number of listeners is 13
157 4.220 VBOSE (DoubleModel.java:920) DoubleModel[RocketFigure:Rotation] adding listener (total 1): net.sf.openrocket.gui.components.UnitSelector[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=,verticalAlignment=CENTER,verticalTextPosition=CENTER]
158 4.222 VBOSE (DoubleModel.java:920) DoubleModel[RocketFigure:Rotation] adding listener (total 2): javax.swing.JSlider$ModelListener@411924e2
159 4.222 VBOSE (DoubleModel.java:920) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@d00960f
160 4.222 VBOSE (DoubleModel.java:942) DoubleModel[RocketFigure:Rotation] removing listener (total 2): javax.swing.plaf.basic.BasicSliderUI$Handler@d00960f
161 4.222 VBOSE (DoubleModel.java:920) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@5b68d79
162 4.437 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
163 4.438 VBOSE (Rocket.java:480) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@a4728ac, current number of listeners is 14
164 4.438 VBOSE (Rocket.java:480) Added ComponentChangeListener net.sf.openrocket.gui.scalefigure.RocketPanel$4@46f0d7af, current number of listeners is 15
165 4.438 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
166 4.459 DEBUG (JarUtil.java:40) Found jar file using codeSource
167 4.459 DEBUG (ExampleDesignFile.java:118) Current jar file is: C:\Program Files\OpenRocket\.\OpenRocket.jar
168 4.473 VBOSE (Rocket.java:480) Added ComponentChangeListener net.sf.openrocket.gui.main.BasicFrame$1@7e87d311, current number of listeners is 16
169 4.554 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 1.00000 user scale, 5669.29 overall scale
170 4.556 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 0.242182 user scale, 1373.00 overall scale
171 4.559 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 0.242182 user scale, 1373.00 overall scale
172 4.560 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 0.242182 user scale, 1373.00 overall scale
173 4.560 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 0.242182 user scale, 1373.00 overall scale
174 4.561 DEBUG (BasicFrame.java:269) ... Setting Initial Selection: [Rocket, Sustainer]
175 4.561 DEBUG (BasicFrame.java:273) BasicFrame instantiation complete
176 4.589 INFO (SwingStartup.java:231) Checking update status
177 4.590 INFO (SwingStartup.java:92) Startup complete
178 4.736 DEBUG (GUIUtil.java:332) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1721,height=935]
179 4.736 DEBUG (GUIUtil.java:337) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
180 4.737 DEBUG (GUIUtil.java:332) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1721,height=935]
181 4.737 DEBUG (GUIUtil.java:337) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
182 4.739 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 0.274814 user scale, 1558.00 overall scale
183 4.740 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 0.274814 user scale, 1558.00 overall scale
184 4.740 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 0.274814 user scale, 1558.00 overall scale
185 4.746 DEBUG (GUIUtil.java:332) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1721,height=935]
186 4.747 DEBUG (GUIUtil.java:337) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
187 4.748 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 0.274814 user scale, 1558.00 overall scale
188 4.748 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 0.274814 user scale, 1558.00 overall scale
189 4.749 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 0.274814 user scale, 1558.00 overall scale
190 4.750 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 0.274814 user scale, 1558.00 overall scale
191 4.757 DEBUG (GUIUtil.java:332) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1721,height=935]
192 4.757 DEBUG (GUIUtil.java:337) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
193 4.799 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 0.274814 user scale, 1558.00 overall scale
194 4.799 VBOSE (AbstractScaleFigure.java:195) ____ Updating RocketFigure to: 0.274814 user scale, 1558.00 overall scale
195 8.219 USER (BasicFrame.java:751) Bug report selected
196 8.221 DEBUG (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

**Comment by hcraigmiller** [comment] 2023-01-17 18:47
Unable to replicate in current unstable.

Please provide screenshots of what you are seeing.

[Windows 11 Pro; Version 22H2; OS Build 22621.521; Windows Feature Experience Pack 1000.22634.1000.0]
java version "11.0.16" 2022-07-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.16+11-LTS-199)

**Comment by hcraigmiller** [comment] 2023-01-25 20:48
The user provided the following screenshots.

![image_01](https://user-images.githubusercontent.com/68821492/214686990-01da9e0b-d0ed-44c3-aa1d-8694b0570bf1.png)
![image_02](https://user-images.githubusercontent.com/68821492/214686998-f661fad7-15a2-4517-9bb4-83c63817112c.png)
![image_03](https://user-images.githubusercontent.com/68821492/214687000-3f778400-73a6-4af2-9af9-a4753a55fc2b.png)
![image_04](https://user-images.githubusercontent.com/68821492/214687001-35c6ec6a-9d4f-442e-a698-c79526bdd448.png)

All attempts to correct with setting changes have failed.

**Comment by neilweinstock** [comment] 2023-02-03 17:06
Do we have any hope of tracking this down?  Not sure what to do with this one.

**Comment by SiboVG** [comment] 2024-08-22 07:39
Duplicate of #1667.

**Closed by SiboVG** 2024-08-22 07:39 UTC
