### ISSUE TITLE
OR saving malformed XML

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#2114] opened 2023-03-13 20:50 UTC
Look at attached ORK file.  There's an XML error in it: 

`<bodytube>
<name>Body Tube</name>
<preset type="BODY_TUBE" manufacturer="Rocketarium" partno="29mm Motor Mount tube 5.5"" digest="ef554285e8e7ab49e1bfc595ac240a5b"/>
`

The double quote in the part number is not being escaped.

[BP Max Altitude.zip](https://github.com/openrocket/openrocket/files/10961791/BP.Max.Altitude.zip)

**Comment by SiboVG** [comment] 2023-03-13 21:51
Duplicate of #2051, already fixed.

**Closed by SiboVG** 2023-03-13 21:51 UTC
Labels: bug, release blocker
