### ISSUE TITLE
[Feature request] upgrade to latest JDK

### ISSUE THREAD

**Issue by DarkTyger** [openrocket/openrocket#2598] opened 2024-11-20 22:38 UTC
### Describe the bug

```
info.openrocket.core.simulation.extension.impl.TestScriptingUtil

  Test testGetLanguages() FAILED

  org.opentest4j.AssertionFailedError: expected: <true> but was: <false>
      at app/org.junit.jupiter.api@5.10.2/org.junit.jupiter.api.AssertionFailureBuilder.build(AssertionFailureBuilder.java:151)
      at app/org.junit.jupiter.api@5.10.2/org.junit.jupiter.api.AssertionFailureBuilder.buildAndThrow(AssertionFailureBuilder.java:132)
      at app/org.junit.jupiter.api@5.10.2/org.junit.jupiter.api.AssertTrue.failNotTrue(AssertTrue.java:63)
      at app/org.junit.jupiter.api@5.10.2/org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:36)
      at app/org.junit.jupiter.api@5.10.2/org.junit.jupiter.api.AssertTrue.assertTrue(AssertTrue.java:31)
      at app/org.junit.jupiter.api@5.10.2/org.junit.jupiter.api.Assertions.assertTrue(Assertions.java:183)
      at app/info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.simulation.extension.impl.TestScriptingUtil.testGetLanguages(TestScriptingUtil.java:40)
      at java.base@23/java.lang.reflect.Method.invoke(Method.java:580)
      at java.base@23/java.util.ArrayList.forEach(ArrayList.java:1597)
      at java.base@23/java.util.ArrayList.forEach(ArrayList.java:1597)

  Test testClearTrustedScripts() PASSED
  Test testHash() PASSED
  Test testSetTrustedScript() PASSED
  Test testGetLanguage() FAILED

  java.lang.NoClassDefFoundError: Could not initialize class org.graalvm.polyglot.Engine$ImplHolder
      at org.graalvm.sdk/org.graalvm.polyglot.Engine.getImpl(Engine.java:367)
      at org.graalvm.sdk/org.graalvm.polyglot.HostAccess$Builder.targetTypeMapping(HostAccess.java:1277)
      at org.graalvm.js.scriptengine/com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.createNashornHostAccess(GraalJSScriptEngine.java:107)
      at org.graalvm.js.scriptengine/com.oracle.truffle.js.scriptengine.GraalJSScriptEngine.<clinit>(GraalJSScriptEngine.java:102)
      at info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.scripting.GraalJSScriptEngineFactory.getScriptEngine(GraalJSScriptEngineFactory.java:36)
      at info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.scripting.ScriptEngineManagerRedux.getEngineByFactory(ScriptEngineManagerRedux.java:260)
      at info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.scripting.ScriptEngineManagerRedux.getEngineByName(ScriptEngineManagerRedux.java:171)
      at info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.simulation.extension.impl.ScriptingUtil.getLanguage(ScriptingUtil.java:69)
      at info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.simulation.extension.impl.TestScriptingUtil.testGetLanguage(TestScriptingUtil.java:32)
      at java.base/java.lang.reflect.Method.invoke(Method.java:580)
      at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
      at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
  Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)' [in thread "Test worker"]
      at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.ensureLibraryInitialized(LibraryFactory.java:384)
      at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.getUncached(LibraryFactory.java:364)
      at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.<init>(LibraryFactory.java:210)
      at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen.<init>(InteropLibraryGen.java:178)
      at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibraryGen.<clinit>(InteropLibraryGen.java:169)
      at java.base/java.lang.Class.forName0(Native Method)
      at java.base/java.lang.Class.forName(Class.java:578)
      at java.base/java.lang.Class.forName(Class.java:557)
      at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.loadGeneratedClass(LibraryFactory.java:791)
      at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolveImpl(LibraryFactory.java:740)
      at org.graalvm.truffle/com.oracle.truffle.api.library.LibraryFactory.resolve(LibraryFactory.java:733)
      at org.graalvm.truffle/com.oracle.truffle.api.interop.InteropLibrary.<clinit>(InteropLibrary.java:2941)
      at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotValueDispatch.<clinit>(PolyglotValueDispatch.java:170)
      at org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotImpl.initialize(PolyglotImpl.java:169)
      at org.graalvm.sdk/org.graalvm.polyglot.impl.AbstractPolyglotImpl.setConstructors(AbstractPolyglotImpl.java:288)
      at org.graalvm.sdk/org.graalvm.polyglot.Engine$1.loadAndValidateProviders(Engine.java:1107)
      at org.graalvm.sdk/org.graalvm.polyglot.Engine$1.run(Engine.java:1067)
      at org.graalvm.sdk/org.graalvm.polyglot.Engine$1.run(Engine.java:1061)
      at java.base/java.security.AccessController.doPrivileged(AccessController.java:319)
      at org.graalvm.sdk/org.graalvm.polyglot.Engine.initEngineImpl(Engine.java:1061)
      at org.graalvm.sdk/org.graalvm.polyglot.Engine$ImplHolder.<clinit>(Engine.java:143)
      at org.graalvm.sdk/org.graalvm.polyglot.Engine.getImpl(Engine.java:367)
      at org.graalvm.sdk/org.graalvm.polyglot.Engine$Builder.build(Engine.java:665)
      at org.graalvm.js.scriptengine/com.oracle.truffle.js.scriptengine.GraalJSEngineFactory.<clinit>(GraalJSEngineFactory.java:70)
      at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
      at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1161)
      at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:548)
      at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:498)
      at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:485)
      at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:785)
      at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:725)
      at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1397)
      at info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.scripting.ScriptEngineManagerRedux.initEngines(ScriptEngineManagerRedux.java:301)
      at info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.scripting.ScriptEngineManagerRedux.init(ScriptEngineManagerRedux.java:277)
      at info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.scripting.ScriptEngineManagerRedux.<init>(ScriptEngineManagerRedux.java:86)
      at info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.simulation.extension.impl.ScriptingUtil.<init>(ScriptingUtil.java:48)
      at info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.simulation.extension.impl.ScriptingUtil$$FastClassByGuice$$fd8899.GUICE$TRAMPOLINE(<generated>)
      at info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.simulation.extension.impl.ScriptingUtil$$FastClassByGuice$$fd8899.apply(<generated>)
      at com.google.guice@7.0.0/com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:82)
      at com.google.guice@7.0.0/com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
      at com.google.guice@7.0.0/com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
      at com.google.guice@7.0.0/com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:300)
      at com.google.guice@7.0.0/com.google.inject.internal.InjectorImpl$1.get(InjectorImpl.java:1148)
      at com.google.guice@7.0.0/com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1186)
      at info.openrocket.core@23.09.SNAPSHOT/info.openrocket.core.file.openrocket.OpenRocketSaverTest.testTrustedScriptEnabledOnLoad(OpenRocketSaverTest.java:242)
      ... 3 more
```

### To Reproduce

1. git clone https://github.com/openrocket/openrocket
1. cd openrocket/
1. gradle clean build

After fixing the `;;` typo ...

Expected
Tests succeed.

Actual
Tests fail.

### OpenRocket version

main

### What platform are you running on?

Linux

### Additional context

Gradle 8.10.2
openjdk 23 2024-09-17
Linux hostname 6.11.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Fri, 01 Nov 2024 03:30:41 +0000 x86_64 GNU/Linux

**Comment by JoePfeiffer** [comment] 2024-11-21 01:49
Changed it to a feature request, since we're still on 17.

**Comment by SiboVG** [comment] 2024-11-21 21:27
Duplicate of #2597.

**Closed by SiboVG** 2024-11-21 21:27 UTC
Labels: bug
