### ISSUE TITLE
"0 degrees" on pods should always extend radially away from the design center

### ISSUE THREAD

**Issue by neilweinstock** [openrocket/openrocket#323] opened 2017-02-03 19:13 UTC
I was trying out the latest unstable release to try out the pods implementation and was alarmed at how 0 degrees on all the pods always pointed straight up, for example:
![image](https://cloud.githubusercontent.com/assets/243872/22604359/3a7e0eca-ea19-11e6-9154-238a869f001b.png)

I don't know if this is a bug or by design but it really should be changed to make the feature useful.  Zero degrees should always point away from the center of the design, so that if I add a single fin to a set of three pods it looks like this:
![image](https://cloud.githubusercontent.com/assets/243872/22604686/b8eae016-ea1a-11e6-86d2-3afa955d0f91.png)

Creating this in the current version is... well let's just say "unpleasant".

I sincerely hope this can be fixed before the next release.  Thanks for considering!

**Comment by teyrana** [comment] 2017-02-04 14:10
Thanks for the heads up.  I wrote that code, and what you describe was definitely NOT intended behavior. I'll look into it when I get a chance.

**Comment by neilweinstock** [comment] 2017-02-04 18:40
Excellent, thanks.  I was sure hoping that wasn't what was intended. [😊]

________________________________

**Comment by ChrisMickelson** [comment] 2017-02-08 18:14
FYI, I've noticed the same behavior on parallel staging/boosters when a small fin is added to the booster tube.

**Comment by ChrisMickelson** [comment] 2017-06-30 04:04
I'll add that perhaps there could be a check-box to align pods radially or unidirectional. For example, pods with fins like Neil mentioned above, or airplane-style pods where you would want vertical stabilizers unidirectional.

**Comment by neilweinstock** [comment] 2017-06-30 13:42
Glad you mentioned that, Chris, since I've been thinking about exactly that issue.  It mainly occurs on two-pod systems, where you'd very commonly want something along these lines:
![pod_angles](https://user-images.githubusercontent.com/243872/27737752-53e87b8a-5d77-11e7-8030-a44f9e862988.png)

0 degrees can still extend radially out from center BT (as shown in the picture), or it can stay vertical; either way works.  The important thing is that the rotational direction of the fins on each pod should be opposite.  This option should apply *only* to two-pod sets; otherwise it doesn't really make any sense.

In fact, in the absence of a selectable option, I'd actually make two-pod sets work like this by default, since it seems *much* more likely to be useful than the other behavior..

Without this capability, entering a design like the one in the picture would require two separate single pods each with its own copy of the fins, etc.

**Comment by teyrana** [comment] 2017-06-30 22:42
@dkingsley Please assign this issue to me.

**Comment by teyrana** [comment] 2017-10-14 15:42
Fix pending at:
https://github.com/teyrana/openrocket/tree/rc1

**Closed** 2018-01-22 12:52 UTC
Labels: next_release
