### ISSUE TITLE
Feature Request: Add straight section to nosecone base

### ISSUE THREAD

**Issue by neutronium95** [openrocket/openrocket#1179] opened 2022-02-27 05:17 UTC
Many nosecones have a section towards the base that is cylindrical. It is pretty easy to model this with an additional section of body tube, but being able to specify that the bottom 3 inches of a nose cone are cylindrical would be convenient.

**Comment by hcraigmiller** [comment] 2022-02-27 05:59
Duplicate of #839; recommend that this issue be close.

**Comment by JoePfeiffer** [comment] 2022-02-27 17:09
Duplicate of #839

**Closed by JoePfeiffer** 2022-02-27 17:09 UTC
Labels: new feature
