### ISSUE TITLE
[Bug] GUI glitching out

### ISSUE THREAD

**Issue by ServerDummy** [openrocket/openrocket#2455] opened 2024-02-05 23:45 UTC
### Describe the bug

The GUI is glitching out, I am on windows 11, uninstalled and reinstalled latest java and graphics drivers, I have had this issue for almost a year now.

https://github.com/openrocket/openrocket/assets/63013446/3b064992-d486-4112-9e54-5845ca0265dc

### To Reproduce

1. open rocket
2. click menu
3. breaks?
...

#### Screenshot(s):
*![image](https://github.com/openrocket/openrocket/assets/63013446/0a421f95-46f3-4a63-9ddf-0f3424c3ddd0)*

#### .ork file:
*(drag-and-drop the file here as a .zip file)*

### OpenRocket version

23.09

### What platform are you running on?

Windows

**Comment by jet689** [comment] 2024-02-18 03:57
yeah I get this to interestingly I get the problem on my pc but not my laptop.

**Comment by jet689** [comment] 2024-02-18 04:23
Actualy yeah I do have a Nvidia GPU. I did use the nvidia driver installed from their driver installer, I will check if there is an update but maybe reverting to the windows recomended might do something idk.

**Comment by jet689** [comment] 2024-02-18 04:37
nope tried all drives nividia game ready studio and windows rec nothing fixed it. looks like the same bug as [https://github.com/openrocket/openrocket/issues/1667](url)

**Comment by ServerDummy** [comment] 2024-02-18 04:46
If you have integrated graphics on your cpu with your desktop maybe try that. I can give it a try in a few days

**Comment by jet689** [comment] 2024-02-18 05:50
nope unforunatly.

**Comment by jet689** [comment] 2024-02-19 00:07
okay so it looks like if you find OpenRocket.exe (it will probalbly be under Program files and openrocket) then you right click it choose properties then the compatability tab and select run this program as administrator it works and it will automatically ask you for administrator permission before running.

**Comment by SiboVG** [comment] 2024-08-22 07:40
Duplicate of #1667.

**Closed by SiboVG** 2024-08-22 07:40 UTC
Labels: bug, UX
