### ISSUE TITLE
centering rings don't consider clustering

### ISSUE THREAD

**Issue by JoePfeiffer** [openrocket/openrocket#1754] opened 2022-10-17 20:31 UTC
If a design includes a cluster of inner tubes, a centering ring for the cluster renders on-screen as if the ring only had a single central hole (which would be correct for a single inner tube). Centering ring mass also doesn't consider holes for all the tubes in the cluster. While this leads to a slight inaccuracy in simulations, it isn't major enough to require an immediate fix.

Curiously, printing a template does show the cluster correctly.
[centering-ring.ork.txt](https://github.com/openrocket/openrocket/files/9804331/centering-ring.ork.txt)

**Comment by SiboVG** [comment] 2022-10-17 20:36
Duplicate of #870.

**Closed by SiboVG** 2022-10-17 20:36 UTC
Labels: bug, Future Release
