### ISSUE TITLE
This Fin marking guide is quite ugly...

### ISSUE THREAD

**Issue by KTesh** [openrocket/openrocket#2109] opened 2023-03-09 15:27 UTC
Ok...  I haven't printed it, but it's pretty ugly if you ask me...

[Estes Red Nova (7266) Fin guide openrocket-10422572677963216927.pdf](https://github.com/openrocket/openrocket/files/10933190/Estes.Red.Nova.7266.Fin.guide.openrocket-10422572677963216927.pdf)

What I really want is a template for pasting onto foamcore or cardboard to keep the fins straight while they're being glued up...  You know...  Something like what you get from Payloadbay's tool section:

https://www.payloadbay.com/index.php?page=Tools&action=FINGUIDES

I'm just worried that someday that site will go away, and we'll be without a useful tool like that.

**Comment by KTesh** [comment] 2023-03-09 15:28
And...  Why can't I post a .ork file here?

**Comment by JoePfeiffer** [comment] 2023-03-09 18:24
I'm not having any luck trying to open the .png file to look at it.
[Estes Red Nova (7266)(2 Stage E to E Mod).zip](https://github.com/openrocket/openrocket/files/10934818/Estes.Red.Nova.7266.2.Stage.E.to.E.Mod.zip)

**Comment by hcraigmiller** [comment] 2023-03-09 18:25
The most significant problem with this design is that phantom and "trick" components are being used for **visual effect**, **_not for construction_**; overlapping launch lugs has been fixed with launch lug instances. When such components are place in-line on the same body tube, the text overlaps.

The secondary problem is that the user is including "comment" type information in the part name, making the part name excessively long. The user should relocate such information from the part name and to the part comment. 

Correcting for the foregoing, the revised fin marking guide is much less "ugly".

![Modified Rev_01](https://user-images.githubusercontent.com/68821492/224119518-5f3a8a47-79c9-4fc7-821e-7a3bd2a1f0fb.png)

Reduced to essentials, this a duplicate issue and should be closed.

**Comment by JoePfeiffer** [comment] 2023-03-09 18:55
Duplicate of #41

**Closed by JoePfeiffer** 2023-03-09 18:55 UTC

**Comment by KTesh** [comment] 2023-03-09 19:13
Thanks for breaking it down for me...  Moving the info to the comments...  OUCH...  I've got a lot of files... My head hurts just thinking about that.
________________________________
