### ISSUE TITLE
Bug: Parachute Automatically Changing Length During Save (Version 22.02 Beta 05)

### ISSUE THREAD

**Issue by JoshA314** [openrocket/openrocket#1736] opened 2022-10-11 20:49 UTC
I am currently using the 22.02 Beta 05 version right now. 
For some reason, every time I save and close my file, the parachute shown in the screenshot automatically adds 5 or 6 inches to the length when I open the file the next time. This is a parachute that I got out of the database. When I inserted the parachute, I did shorten the length from what is in the database because I found I could pack it smaller, so I don't know if this is what caused the issue or not.

![image](https://user-images.githubusercontent.com/94728561/195193986-181c5e91-fc4e-41a5-97d8-7f7badabc411.png)

![image](https://user-images.githubusercontent.com/94728561/195194268-41537dab-cff1-4f7d-8f33-a2e5f512dd6e.png)

**Comment by SiboVG** [comment] 2022-10-12 08:42
Hi, thanks for the bug reports, this is a duplicate of #1723. The bug has since been fixed.

**Closed by SiboVG** 2022-10-12 08:42 UTC
