### ISSUE TITLE
[Bug] Jogl can not work on jdk17

### ISSUE THREAD

**Issue by ZCY571864845** [openrocket/openrocket#2380] opened 2023-10-21 11:53 UTC
### Describe the bug

Can not use openrocket figure3d view type on jdk17.
GLException:Unable to determine GraphicsGonfiguration.

### To Reproduce

1. Open or create any rocket.
2. Change view type to 3D Figure.
3. Openrocket throw uncaught exception.

#### Screenshot(s):
*(drag-and-drop the screenshot(s) here)*
<img width="459" alt="20231021132637" src="https://github.com/openrocket/openrocket/assets/19361354/1c14ec9a-8a9d-45d9-84ce-aa086c7bf4a4">

#### .ork file:
*(drag-and-drop the file here as a .zip file)*

### OpenRocket version

unstable

### What platform are you running on?

Windows

**Comment by SiboVG** [comment] 2023-10-21 11:55
Thank you for your report, this is a duplicate of #2336.

**Closed by SiboVG** 2023-10-21 11:55 UTC
Labels: bug

**Comment by ZCY571864845** [comment] 2023-10-21 12:59
I add VM arguments:
--add-exports java.base/java.lang=ALL-UNNAMED
--add-exports java.desktop/sun.awt=ALL-UNNAMED
--add-exports java.desktop/sun.java2d=ALL-UNNAMED
and it works.
but,I find it is very hard to select a component on 3d view type.

**Comment by SiboVG** [comment] 2023-10-21 13:01
> I add VM arguments: --add-exports java.base/java.lang=ALL-UNNAMED --add-exports java.desktop/sun.awt=ALL-UNNAMED --add-exports java.desktop/sun.java2d=ALL-UNNAMED and it works. but,I find it is very hard to select a component on 3d view type.

The 3D component selection code is very inefficient, so it can sometimes not react the way you'd want it. If it makes you feel any better, 3D component selection simply doesn't work on macOS 🙃.

**Comment by ZCY571864845** [comment] 2023-10-21 13:18
3D component selection seems work better on version OpenRocket 22.02(jdk11).Maybe jogl do not support very friendly on jdk17.

**Comment by ZCY571864845** [comment] 2023-10-21 13:44
I Change the jdk version to 11,3D component selection also work hard.Obviously,It is not cause by jogl compatibility on jdk17.

**Comment by SiboVG** [comment] 2023-10-21 14:00
> I Change the jdk version to 11,3D component selection also work hard.Obviously,It is not cause by jogl compatibility on jdk17.

Okay, thanks for testing!
