### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by DalekCaiomhin** [openrocket/openrocket#1964] opened 2023-01-10 08:38 UTC
Clusters don't have that many holes in their centering rings.  Rings only have one hole.  Fin tabs also go to the imaginary center and not necessarily the motor tube.  How about custom motors, maybe liquid propellants?

**Comment by hcraigmiller** [comment] 2023-01-10 09:16
> Clusters don't have that many holes in their centering rings. Rings only have one hole.

This is a known issue, please see Issue #870.

> How about custom motors, maybe liquid propellants?

OpenRocket incorporates the ThrustCurve motor database. In addition, users can add their own custom motors by placing a custom motor file in their motor directory, the location of which may be found/set here: 

![Custom Motors](https://user-images.githubusercontent.com/68821492/211509701-f774f63b-6aae-4f58-b88b-7ecbbcda6478.png)

> Fin tabs also go to the imaginary center and not necessarily the motor tube.

This is likely the result of user error, not properly positioning the motor tube and centering rings below the fins. For the automatic fin tube option to function correctly, a "motor tube" and "two" centering rings must be positioned below the fins. Like this:

![Fin Tabs](https://user-images.githubusercontent.com/68821492/211507467-6b920a77-78ea-4ecd-ad6a-52f4f4a96bb9.png)
[Fin Tabs.zip](https://github.com/openrocket/openrocket/files/10380853/Fin.Tabs.zip)

Please review your design to determine whether this is what you are experiencing. If so, please close this issue. If not, please post the design file for the issue that you are reporting.

I Hope this helps.

**Comment by JoePfeiffer** [comment] 2023-02-03 21:35
Duplicate of 870

**Closed by JoePfeiffer** 2023-02-03 21:35 UTC
