### ISSUE TITLE
Error On Launching the 22.02.beta.01 JAR file

### ISSUE THREAD

**Issue by silversurfer77** [openrocket/openrocket#1165] opened 2022-02-26 02:50 UTC
---------- Bug report ----------

Please include a description about what actions you were performing when the exception occurred:
(You can edit text directly in this window)

1. Downloaded the new/beta 22.02.beta.01 .JAR file (not the installer)
2. Downloaded and Installed Java 64 bit

- java version "1.8.0_321"
- Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
- Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)

4. Running on Windows 11
5. Double clicked the .JAR file and OpenRocket opened and an error dialog appeared immediately
6. I click CLOSE on the error dialog box and OR seems to be working OK...but I haven't really tested anything yet.
Include your email address (optional; it helps if we can contact you in case we need additional information):
dankunkel@gmail.com

(Do not modify anything below this line.)
---------- Exception stack trace ----------
java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;)Ljava/util/List; at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.getLatestReleaseJSON(UpdateInfoRetriever.java:362) at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.runUpdateFetcher(UpdateInfoRetriever.java:142) at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.run(UpdateInfoRetriever.java:123)

---------- Thread information ----------
Thread[UpdateInfoFetcher,6,main]

---------- System information ----------
OpenRocket version: 22.02.beta.01
OpenRocket source: default
OpenRocket location: C:\Users\danku\OneDrive\Desktop\OpenRocket-22.02.beta.01.jar
JOGL version: 2.4.0-rc-20210111
Current default locale: en_US
System properties:
awt.toolkit=sun.awt.windows.WToolkit
file.encoding=Cp1252
file.encoding.pkg=sun.io
file.separator=\
java.awt.graphicsenv=sun.awt.Win32GraphicsEnvironment
java.awt.printerjob=sun.awt.windows.WPrinterJob
java.class.path=C:\Users\danku\OneDrive\Desktop\OpenRocket-22.02.beta.01.jar
java.class.version=52.0
java.endorsed.dirs=C:\Program Files\Java\jre1.8.0_321\lib\endorsed
java.ext.dirs=C:\Program Files\Java\jre1.8.0_321\lib\ext;C:\windows\Sun\Java\lib\ext
java.home=C:\Program Files\Java\jre1.8.0_321
java.io.tmpdir=C:\Users\danku\AppData\Local\Temp\
java.library.path=C:\Program Files\Java\jre1.8.0_321\bin;C:\windows\Sun\Java\bin;C:\windows\system32;C:\windows;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Users\danku\AppData\Local\Microsoft\WindowsApps;;.
java.runtime.name=Java(TM) SE Runtime Environment
java.runtime.version=1.8.0_321-b07
java.specification.name=Java Platform API Specification
java.specification.vendor=Oracle Corporation
java.specification.version=1.8
java.util.Arrays.useLegacyMergeSort=true
java.vendor=Oracle Corporation
java.vendor.url=http://java.oracle.com/
java.vendor.url.bug=http://bugreport.sun.com/bugreport/
java.version=1.8.0_321
java.vm.info=mixed mode
java.vm.name=Java HotSpot(TM) 64-Bit Server VM
java.vm.specification.name=Java Virtual Machine Specification
java.vm.specification.vendor=Oracle Corporation
java.vm.specification.version=1.8
java.vm.vendor=Oracle Corporation
java.vm.version=25.321-b07
jnlp.jogamp.tmp.cache.root=jln2663370734863557396
line.separator=\u000d\u000a
os.arch=amd64
os.name=Windows 11
os.version=10.0
path.separator=;
sun.arch.data.model=64
sun.awt.enableExtraMouseButtons=true
sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
sun.boot.class.path=C:\Program Files\Java\jre1.8.0_321\lib\resources.jar;C:\Program Files\Java\jre1.8.0_321\lib\rt.jar;C:\Program Files\Java\jre1.8.0_321\lib\sunrsasign.jar;C:\Program Files\Java\jre1.8.0_321\lib\jsse.jar;C:\Program Files\Java\jre1.8.0_321\lib\jce.jar;C:\Program Files\Java\jre1.8.0_321\lib\charsets.jar;C:\Program Files\Java\jre1.8.0_321\lib\jfr.jar;C:\Program Files\Java\jre1.8.0_321\classes
sun.boot.library.path=C:\Program Files\Java\jre1.8.0_321\bin
sun.cpu.endian=little
sun.cpu.isalist=amd64
sun.desktop=windows
sun.io.unicode.encoding=UnicodeLittle
sun.java.command=C:\Users\danku\OneDrive\Desktop\OpenRocket-22.02.beta.01.jar
sun.java.launcher=SUN_STANDARD
sun.jnu.encoding=Cp1252
sun.management.compiler=HotSpot 64-Bit Tiered Compilers
sun.os.patch.level=
user.country=US
user.dir=C:\Users\danku\OneDrive\Desktop
user.home=C:\Users\danku
user.language=en
user.name=danku
user.script=
user.timezone=America/Chicago
user.variant=
---------- Error log ----------
1 0.000 INFO (SwingStartup.java:62) Starting up OpenRocket version 22.02.beta.01
2 0.000 INFO (SwingStartup.java:65) Checking for graphics head
3 0.031 INFO (SwingStartup.java:76) Moving startup to EDT
4 0.047 INFO (SwingStartup.java:130) Initializing the splash screen
5 0.079 INFO (SwingStartup.java:134) Registering exception handler
6 0.079 INFO (SwingStartup.java:140) Loading databases
7 0.719 INFO (TranslatorProvider.java:49) Using default locale en_US
8 0.719 INFO (TranslatorProvider.java:61) Set up translation for locale en_US, debug.currentFile=messages.properties
9 0.719 INFO (MotorDatabaseLoader.java:87) Starting reading serialized motor database
10 0.719 INFO (ComponentPresetDatabaseLoader.java:93) Loading component presets from datafiles/presets
13 0.727 INFO (SwingStartup.java:152) Starting update check
14 0.734 INFO (SwingStartup.java:161) Setting best LAF
18 0.822 INFO (SwingStartup.java:173) Opening main application window
19 0.837 INFO (BasicFrame.java:1638) New action initiated
28 1.169 INFO (MotorDatabaseLoader.java:93) Ending reading serialized motor database, motorCount=1878
29 1.194 INFO (MotorDatabaseLoader.java:68) Starting reading user-defined motors
30 1.194 INFO (MotorDatabaseLoader.java:78) Ending reading user-defined motors, motorCount=1878
60 0.000 DEBUG (-) ===== 36 DEBUG lines removed =====
60 1.553 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/estes_ps2.orc contained 30 presets
61 1.553 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/fliskits-legacy.orc
62 1.553 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/fliskits-legacy.orc
63 1.586 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/fliskits-legacy.orc contained 160 presets
64 1.586 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/generic_materials.orc
65 1.586 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/generic_materials.orc
66 1.601 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/generic_materials.orc contained 0 presets
67 1.601 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/giantleaprocketry-legacy.orc
68 1.601 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/giantleaprocketry-legacy.orc
69 1.609 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/giantleaprocketry-legacy.orc contained 74 presets
70 1.609 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/loc_precision.orc
71 1.609 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/loc_precision.orc
72 1.617 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/loc_precision.orc contained 64 presets
73 1.617 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/madcow.orc
74 1.617 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/madcow.orc
75 1.656 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/madcow.orc contained 240 presets
76 1.656 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/mpc.orc
77 1.656 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/mpc.orc
78 1.670 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/mpc.orc contained 49 presets
79 1.670 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/publicmissiles-legacy.orc
80 1.670 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/publicmissiles-legacy.orc
81 1.701 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/publicmissiles-legacy.orc contained 115 presets
82 1.702 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/quest.orc
83 1.702 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/quest.orc
84 1.720 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/quest.orc contained 71 presets
85 1.721 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/semroc-legacy.orc
86 1.721 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/semroc-legacy.orc
91 0.000 VBOSE (-) ===== 10 VBOSE lines removed =====
91 1.803 VBOSE (AbstractChangeSource.java:25) Adding change listeners, listener count is now 1
92 1.959 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/semroc-legacy.orc contained 874 presets
93 1.960 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/semroc.orc
94 1.960 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/semroc.orc
95 1.988 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.dialogs.flightconfiguration.MotorMountTableModel@2855ba20, current number of listeners is 7
96 1.988 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.FlightConfigurableTableModel@423e6f1, current number of listeners is 8
97 1.988 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.RecoveryConfigurationPanel$$Lambda$41/751000847@65634fb4, current number of listeners is 9
98 2.003 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.SeparationConfigurationPanel$4@406ebf61, current number of listeners is 10
99 2.035 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
100 2.056 DEBUG (UpdateInfoRetriever.java:229) Update checker response code: 200
101 2.065 DEBUG (RocketFigure3d.java:140) Initializing RocketFigure3D OpenGL Canvas
102 2.065 DEBUG (RocketFigure3d.java:142) Setting up GL capabilities...
103 2.065 VBOSE (RocketFigure3d.java:144) GL - Getting Default Profile
104 2.235 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/semroc.orc contained 1676 presets
105 2.258 DEBUG (ComponentPresetDatabaseLoader.java:117) loading from file: datafiles/presets/top_flight.orc
106 2.258 DEBUG (OpenRocketComponentLoader.java:26) Loading presets from file datafiles/presets/top_flight.orc
107 2.266 DEBUG (OpenRocketComponentLoader.java:35) ComponentPreset file datafiles/presets/top_flight.orc contained 34 presets
108 2.307 DEBUG (ComponentPresetDatabaseLoader.java:59) Time to load presets: 1588ms 4311 loaded from 21 files
109 3.232 VBOSE (RocketFigure3d.java:147) GL - creating GLCapabilities
110 3.232 VBOSE (RocketFigure3d.java:151) GL - setSampleBuffers
111 3.232 VBOSE (RocketFigure3d.java:154) GL - setNumSamples
112 3.232 VBOSE (RocketFigure3d.java:164) GL - Creating GLCanvas
113 3.232 VBOSE (RocketFigure3d.java:168) GL - Registering as GLEventListener on canvas
114 3.232 VBOSE (RocketFigure3d.java:171) GL - Adding canvas to this JPanel
115 3.232 VBOSE (RocketFigure3d.java:174) GL - Setting up mouse listeners
116 3.232 VBOSE (RocketFigure3d.java:177) GL - Rasterizing Carets
117 3.248 VBOSE (DoubleModel.java:897) DoubleModel[constant=0.0] adding listener (total 1): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$1@3f326f7e
118 3.248 VBOSE (DoubleModel.java:897) DoubleModel[constant=0.0] adding listener (total 2): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
119 3.248 VBOSE (DoubleModel.java:897) DoubleModel[constant=0.0] adding listener (total 3): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=]
120 3.248 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
121 3.248 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
122 3.248 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
123 3.248 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
124 3.248 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
125 3.264 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
126 3.264 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@712953ff, current number of listeners is 11
127 3.270 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@6ef8e78a, current number of listeners is 12
128 3.270 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@158c2b1a, current number of listeners is 13
129 3.270 VBOSE (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 1): net.sf.openrocket.gui.components.UnitSelector[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=,verticalAlignment=CENTER,verticalTextPosition=CENTER]
130 3.276 VBOSE (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 2): javax.swing.JSlider$ModelListener@4f1c7aa0
131 3.276 VBOSE (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@3823031f
132 3.276 VBOSE (DoubleModel.java:919) DoubleModel[RocketFigure:Rotation] removing listener (total 2): javax.swing.plaf.basic.BasicSliderUI$Handler@3823031f
133 3.276 VBOSE (DoubleModel.java:897) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@253b6453
134 3.506 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
135 3.506 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@f758fd5, current number of listeners is 14
136 3.506 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.scalefigure.RocketPanel$4@6a93800b, current number of listeners is 15
137 3.506 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
138 3.522 DEBUG (JarUtil.java:40) Found jar file using codeSource
139 3.522 DEBUG (ExampleDesignFile.java:118) Current jar file is: C:\Users\danku\OneDrive\Desktop\OpenRocket-22.02.beta.01.jar
140 3.540 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@70d9c8c9, current number of listeners is 16
141 3.547 VBOSE (Rocket.java:440) Added ComponentChangeListener net.sf.openrocket.gui.main.BasicFrame$1@7893aaf6, current number of listeners is 17
142 3.655 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 1.00000 user scale, 3779.53 overall scale
143 3.655 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.413544 user scale, 1563.00 overall scale
144 3.655 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.413544 user scale, 1563.00 overall scale
145 3.655 DEBUG (BasicFrame.java:279) ... Setting Initial Selection: [Rocket, Sustainer]
146 3.655 DEBUG (BasicFrame.java:283) BasicFrame instantiation complete
147 3.689 INFO (SwingStartup.java:195) Checking update status
148 3.689 INFO (SwingStartup.java:84) Startup complete
149 3.752 DEBUG (GUIUtil.java:311) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1936,height=1048]
150 3.752 DEBUG (GUIUtil.java:316) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
151 3.752 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
152 3.752 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
153 3.752 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
154 3.768 DEBUG (GUIUtil.java:311) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1936,height=1048]
155 3.768 DEBUG (GUIUtil.java:316) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
156 3.768 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
157 3.768 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
158 3.768 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
159 3.768 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
160 3.788 DEBUG (GUIUtil.java:311) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=1936,height=1048]
161 3.788 DEBUG (GUIUtil.java:316) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
162 3.788 DEBUG (UpdateInfoRetriever.java:229) Update checker response code: 200
163 3.817 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
164 3.817 VBOSE (AbstractScaleFigure.java:191) ____ Updating RocketFigure to: 0.468577 user scale, 1771.00 overall scale
165 3.964 ERROR (SwingExceptionHandler.java:48) Handling uncaught exception on thread=Thread[UpdateInfoFetcher,6,main]
> java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;)Ljava/util/List; > at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.getLatestReleaseJSON(UpdateInfoRetriever.java:362) > at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.runUpdateFetcher(UpdateInfoRetriever.java:142) > at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.run(UpdateInfoRetriever.java:123)
166 3.964 STDERR (SwingExceptionHandler.java:49) java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;)Ljava/util/List;
167 3.964 STDERR (SwingExceptionHandler.java:49) at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.getLatestReleaseJSON(UpdateInfoRetriever.java:362)
168 3.964 STDERR (SwingExceptionHandler.java:49) at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.runUpdateFetcher(UpdateInfoRetriever.java:142)
169 3.964 STDERR (SwingExceptionHandler.java:49) at net.sf.openrocket.communication.UpdateInfoRetriever$UpdateInfoFetcher.run(UpdateInfoRetriever.java:123)
170 3.964 INFO (SwingExceptionHandler.java:64) Exception handler not on EDT, invoking dialog on EDT
171 3.964 INFO (SwingExceptionHandler.java:201) Showing Exception dialog
172 19.516 USER (SwingExceptionHandler.java:220) User requested sending bug report
173 19.518 DEBUG (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

**Comment by JoePfeiffer** [comment] 2022-02-26 05:17
The new release will not run on Java 8 (getting away from that prehistoric version was one of the goals!).  If you must run the jar for some reason, you need to be using at least (and preferably) Java 11. The packaged installers include a copy of the Java 11 runtime.

**Comment by hcraigmiller** [comment] 2022-02-26 08:29
BUG CONFIRMED: On first run of the .jar file, the following message appeared. After clicking _Okay_, the message disappeared and OR opened with no detected anomalous behavior. Closing and reopening OR did not trigger a repeat of the message.

![1165 01 Jar_Run_Error](https://user-images.githubusercontent.com/68821492/155836225-9d1a5650-d735-48ae-a2ad-2dae8e4169e6.png)

[Windows 11 Pro, Version 21H2, Build 22000.434, Windows Feature Experience Pack 1000.22000.434.0]

**Comment by JoePfeiffer** [comment] 2022-02-26 17:38
Now I'm confused -- I didn't think OR would run at all under Java 8 (and my first response was too hasty).

**Comment by neilweinstock** [comment] 2022-02-26 18:03
My recollection from the past is that it kind of runs, sometimes, with some problems.  Definitely not recommended.  Is there a way to check for that in the app and refuse to run (or put up a helpful message) if a bad JRE is used?

**Comment by hcraigmiller** [comment] 2022-02-26 20:04
Jar file warning added to Wiki at http://wiki.openrocket.info/Other_Installations, with instructions.

**Comment by neilweinstock** [comment] 2022-02-26 20:30
Closing this because it's a documentation issue, and that is "fixed".

**Comment by silversurfer77** [comment] 2022-02-27 17:46
It appears that you cannot download and install the Java 11 JRE. So unless you are a developer with a license, the JAR is kinda useless. I prefer the JAR file since it is portable and doesn't need to be installed.

I am hoping it is possible to install OR using the installer, then uninstall, and preserve Java 11 so I can run the standalone JAR.

**Comment by SiboVG** [comment] 2022-02-28 16:18
> It appears that you cannot download and install the Java 11 JRE. So unless you are a developer with a license, the JAR is kinda useless. I prefer the JAR file since it is portable and doesn't need to be installed.

There are tools to switch between Java-versions. jEnv is a very good one for Linux and macOS. I believe there are similar alternatives for Windows. If you're really having troubles with installing Java 11 JRE I'd suggest you check out a tool like jEnv.

**Comment by JoePfeiffer** [comment] 2022-02-28 16:28
> It appears that you cannot download and install the Java 11 JRE. So unless you are a developer with a license, the JAR is kinda useless. I prefer the JAR file since it is portable and doesn't need to be installed.
> 
> I am hoping it is possible to install OR using the installer, then uninstall, and preserve Java 11 so I can run the standalone JAR.

Note JRE is, to the best of my knowledge, not available separately whether you've got a license or not.  You can certainly download the JDK -- I got it for my Win10 box from https://adoptium.net/releases.html?variant=openjdk11, it works fine, and I have no license.

**Closed** 2022-02-28 16:28 UTC
Labels: documentation
