### ISSUE TITLE
Fin 3D appearance goes transparent on non-conical transitions

### ISSUE THREAD

**Issue by sjh114961** [openrocket/openrocket#1646] opened 2022-09-06 20:26 UTC

**Comment by sjh114961** [comment] 2022-09-06 20:30
Using these 2 models as reference, when the fin tabs are used the fins go transparent even if opacity set to 100%. Both models in same zip file the R1 version has no tabs the other model does.
[v2_18mm.zip](https://github.com/openrocket/openrocket/files/9500514/v2_18mm.zip)

**Comment by SiboVG** [comment] 2022-09-06 20:46
The issue you're talking about is a duplicate of #1597, which is already fixed and will be included in beta 5.

**However**, when testing this on the latest unstable branch, I noticed that the fins go "transparent" when the transition is non-conical, even when they have no tabs. So there is a new issue created due to some of the recent bug fixes in fins on non-conical transitions.

**Comment by sjh114961** [comment] 2022-09-06 21:13
One of the models in the zip file does not have the fin tabs and is NOT conical and seems to work.

**Comment by SiboVG** [comment] 2022-09-06 21:19
> One of the models in the zip file does not have the fin tabs and is NOT conical and seems to work.

That's for beta 4, not for the latest unstable branch of this repo.

**Comment by hcraigmiller** [comment] 2022-09-07 03:02
If you scale the rocket 200% (fin tabs and no fin tabs), this is what happens with the parachute _**and fins**_:

![Tab 200](https://user-images.githubusercontent.com/68821492/188778139-d0fad988-68a4-4266-84dc-06c3489fdd55.png)
![Tab 200 Parachute](https://user-images.githubusercontent.com/68821492/188778958-480b6d1d-315f-489c-9baa-6821012f282e.png)

As to the parachute, current unstable does the same thing, I'll create a new parachute issue?

Build 992

[Windows 11 Pro; Version 21H2; OS Build 22000.739; Windows Feature Experience Pack 1000.22000.739.0]
[Java "11.0.15" 2022-04-19 LTS; Java(TM) SE Runtime Environment 18.9 (build 11.0.15+8-LTS-149)]

**Closed** 2022-09-10 21:03 UTC
Labels: bug, beta blocker
