### ISSUE TITLE
[Bug] Can't create a new motor configuration or edit the existing one

### ISSUE THREAD

**Issue by fabioski01** [openrocket/openrocket#1666] opened 2022-09-11 16:50 UTC
---------- Bug report ----------
I'm using a file with a single motor configuration and I wanted to add a new one, but I can't.
Motors & Configuration tab > New Configuration / Edit configuration > Uncaught Exception
The same happens if I duplicate the existing configuration (however it duplicates it successfully), or if I try to edit the existing configuration (doesn't open any window). I can remove configurations. If I remove all configurations nothing changes.

I attach a txt with the bug report
[bug report.txt](https://github.com/openrocket/openrocket/files/9543107/bug.report.txt)

**Comment by SiboVG** [comment] 2022-09-11 16:56
Thanks for the bug report. This is a duplicate of #1561. Beta 5 (released soon) will be shipped with a fix for this bug.

**Closed by SiboVG** 2022-09-11 16:56 UTC
