### ISSUE TITLE
[Feature] Allow numeric inputs with explicit units

### ISSUE THREAD

**Issue by broofa** [openrocket/openrocket#1644] opened 2022-09-06 13:03 UTC
The units I happen "think in" don't always align with my preferred unit settings.  For example, I generally prefer to have a consistent system of units ("default metric"),  however, I'll often want to enter values in the units listed on material provided by a manufacturer, or units used by the person I'm discussing a design with, or the units on whatever tape measure or calipers or scale I happen to have at hand.

Thus, it would be helpful to be able to type in values such as  "`5 mm`" or "`12 lb`", "123 gm", or "`5'3"`" into numeric fields and have those convert automatically to my preferred units.

**Comment by SiboVG** [comment] 2022-09-06 13:16
Duplicate of #1633?

**Closed by SiboVG** 2022-09-06 13:16 UTC
