### ISSUE TITLE
Supper buggy UI glitches

### ISSUE THREAD

**Issue by Reysean05** [openrocket/openrocket#1396] opened 2022-06-01 04:07 UTC
Hello, ive recently been trying to use open rocket on my windows PC but the UI has been super glitchy making it unusable. it boots up fine but after a few seconds opening any menu causes more to pop out everywhere. I have updated java, updated graphics card drivers, reinstalled, restarted my PC. I have an rtx 3070, 32gb of ram, and a Ryzen 5600x. Please help I need this software.

![Screenshot (21)](https://user-images.githubusercontent.com/102936811/171325385-e94be2e8-924f-4e06-ad59-bc31bc15ca4d.png)
.

**Comment by hcraigmiller** [comment] 2022-06-01 04:14
Have you tried this... http://wiki.openrocket.info/Downloading_%26_Installing#Check_Settings, This looks like a display setting problem that others experienced

**Comment by Reysean05** [comment] 2022-06-02 02:53
> Have you tried this... http://wiki.openrocket.info/Downloading_%26_Installing#Check_Settings, This looks like a display setting problem that others experienced

That seems to of fixed it. Much appreciated.

**Comment by Reysean05** [comment] 2022-06-02 02:55
> Have you tried this... http://wiki.openrocket.info/Downloading_%26_Installing#Check_Settings, This looks like a display setting problem that others experienced

That did not work :(. whats strange is it seems to take some time to take effect

**Comment by SiboVG** [comment] 2022-06-08 16:20
Did you try disabling anti-aliasing in the NVIDIA driver?

**Comment by Reysean05** [comment] 2022-06-18 05:54
> Did you try disabling anti-aliasing in the NVIDIA driver?

didnt work

**Comment by thzero** [comment] 2022-06-26 18:42
I've seen that on the current 15 version.   Haven't seen it at all on the betas, or even the old version running under java 11 after ogl updates.

I have same card, but only Intel chip.

This is how I've run the 15.04 version.  Not doing this on the new one, but it may be worth trying.

"C:\Program Files\Eclipse Adoptium\jdk-8.0.312.7-hotspot\bin\java" -Dsun.java2d.d3d=false -jar OpenRocket-15.04.jar

**Comment by SiboVG** [comment] 2024-08-22 07:40
Duplicate of #1667.

**Closed by SiboVG** 2024-08-22 07:40 UTC
